// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

type Snapshot struct {
	UserName    string
	StoreName   string
	CreditLimit decimal.Decimal
	SnapshotAt  pgtype.Timestamp
	CreatedAt   pgtype.Timestamp
}
